name: CI

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check notebook runs
      working-directory: notebooks
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute 01_eda.ipynb --output executed_01_eda.ipynb --allow-errors
        jupyter nbconvert --to notebook --execute 02_hypothesis_testing.ipynb --output executed_02_hypothesis_testing.ipynb --allow-errors