name: CI

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check notebook runs
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute notebooks/01_eda.ipynb --output executed_notebook.ipynb